# MLZoomCamp
## 1.7 Introduction to NumPy

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [2]:
np

<module 'numpy' from '/Users/lecha/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

### Creating arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(5, 3.4)

array([3.4, 3.4, 3.4, 3.4, 3.4])

In [6]:
l = [1,2,3,4,5]
a = np.array(l)
a

array([1, 2, 3, 4, 5])

In [7]:
a[2]

3

In [8]:
a[2] = 100
a

array([  1,   2, 100,   4,   5])

In [9]:
np.arange(9+1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3, 9+1)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimensional arrays

In [12]:
# create zeros array with 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [14]:
a[1, 1]

5

In [15]:
a[1, 1] = 100
a

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [16]:
a[0]

array([1, 2, 3])

In [17]:
a[0] = [100, 200, 300]
a

array([[100, 200, 300],
       [  4, 100,   6],
       [  7,   8,   9]])

In [18]:
a[:, 2]

array([300,   6,   9])

### Randomly generated arrays

In [19]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.436 , 0.0259],
       [0.5497, 0.4353],
       [0.4204, 0.3303],
       [0.2046, 0.6193],
       [0.2997, 0.2668]])

In [20]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.436 , 0.0259],
       [0.5497, 0.4353],
       [0.4204, 0.3303],
       [0.2046, 0.6193],
       [0.2997, 0.2668]])

In [21]:
np.random.rand(5, 2)

array([[0.6211, 0.5291],
       [0.1346, 0.5136],
       [0.1844, 0.7853],
       [0.854 , 0.4942],
       [0.8466, 0.0796]])

In [22]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.4168, -0.0563],
       [-2.1362,  1.6403],
       [-1.7934, -0.8417],
       [ 0.5029, -1.2453],
       [-1.058 , -0.909 ]])

In [23]:
np.random.seed(2)
np.random.randn(5, 2) * 100

array([[ -41.6758,   -5.6267],
       [-213.6196,  164.0271],
       [-179.3436,  -84.1747],
       [  50.2881, -124.5288],
       [-105.7952,  -90.9008]])

### Element-wise operations

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [26]:
a / b + 10

array([10.    , 10.6944, 11.0204, 11.1719, 11.2346])

### Comparison operations

In [27]:
a

array([0, 1, 2, 3, 4])

In [28]:
a > 2

array([False, False, False,  True,  True])

In [29]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [30]:
a > b

array([False, False,  True,  True,  True])

In [31]:
a[a > b]

array([2, 3, 4])

### Summarizing operations

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a.std()

1.4142135623730951

In [34]:
a.min()

0

In [35]:
a.max()

4

In [36]:
a.sum()

10