In [1]:
import numpy as np

In [2]:
u = np.array([2, 7, 5, 6])
v = np.array([1, .5, 2, 1])

### Vector operations

In [3]:
# addition 
u + v

array([3. , 7.5, 7. , 7. ])

In [4]:
# subtraction 
u - v

array([1. , 6.5, 3. , 5. ])

In [5]:
# scalar multiplication 
2 * v

array([2., 1., 4., 2.])

### Multiplication

##### Vector-vector multiplication

In [6]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [7]:
u = np.array([2, 7, 5, 6])
v = np.array([1, .5, 2, 1])

In [8]:
vector_vector_multiplication(u, v)

21.5

In [9]:
u.dot(v)

21.5

##### Matrix-vector multiplication

In [10]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [11]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

v = np.array([1, .5, 2, 1])

In [12]:
matrix_vector_multiplication(U,v)

array([20. ,  6. ,  8.5])

##### Matrix-matrix multiplication

In [13]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [14]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

V = np.array([
    [1, 1, 2],
    [0, .5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

##### Identity matrix

In [15]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
V = np.array([
    [1, 1, 2],
    [0, .5, 1],
    [0, 2, 1]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [17]:
print(matrix_matrix_multiplication(V,I))
matrix_matrix_multiplication(I,V) == matrix_matrix_multiplication(V,I)

[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### Inverse

In [18]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)

In [19]:
inv.dot(V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])