In [1]:
import numpy as np

In [2]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

### Vector operations

In [3]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [4]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [5]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

### Multiplication

##### Vector-vector multiplication

In [6]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

##### Matrix-vector multiplication

In [7]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

##### Matrix-matrix multiplication

In [8]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

##### Identity matrix

In [9]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Inverse

In [10]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)